Загружаем датасет

In [88]:
import pandas as pd

pokemon = pd.read_csv("../data/Pokemon_preprocessed.csv", index_col=0)
pokemon.info()
pokemon.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 800 entries, 0 to 799
Data columns (total 28 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Name        800 non-null    object
 1   Total       800 non-null    int64 
 2   HP          800 non-null    int64 
 3   Attack      800 non-null    int64 
 4   Defense     800 non-null    int64 
 5   Sp. Atk     800 non-null    int64 
 6   Sp. Def     800 non-null    int64 
 7   Speed       800 non-null    int64 
 8   Generation  800 non-null    int64 
 9   Legendary   800 non-null    bool  
 10  t_Bug       800 non-null    int64 
 11  t_Dark      800 non-null    int64 
 12  t_Dragon    800 non-null    int64 
 13  t_Electric  800 non-null    int64 
 14  t_Fairy     800 non-null    int64 
 15  t_Fighting  800 non-null    int64 
 16  t_Fire      800 non-null    int64 
 17  t_Flying    800 non-null    int64 
 18  t_Ghost     800 non-null    int64 
 19  t_Grass     800 non-null    int64 
 20  t_Ground  

Name  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0              Bulbasaur    318  45      49       49       65       65     45   
1                Ivysaur    405  60      62       63       80       80     60   
2               Venusaur    525  80      82       83      100      100     80   
3  VenusaurMega Venusaur    625  80     100      123      122      120     80   
4             Charmander    309  39      52       43       60       50     65   

   Generation  Legendary  ...  t_Ghost  t_Grass  t_Ground  t_Ice  t_Normal  \
0           1      False  ...        0        1         0      0         0   
1           1      False  ...        0        1         0      0         0   
2           1      False  ...        0        1         0      0         0   
3           1      False  ...        0        1         0      0         0   
4           1      False  ...        0        0         0      0         0   

   t_Poison  t_Psychic  t_Rock  t_Steel  t_Water  
0         1          0       0        0        0  
1         1          0       0        0        0  
2         1          0       0        0        0  
3         1          0       0        0        0  
4         0          0       0        0        0  

[5 rows x 28 columns]

Разбиваем данные на параметры входные и целевые.

In [89]:
X = pokemon.drop(["Generation","Name"], axis=1).values
Y = pokemon.iloc[:, 8].values

In [90]:
print(X)

[[318 45 49 ... 0 0 0]
 [405 60 62 ... 0 0 0]
 [525 80 82 ... 0 0 0]
 ...
 [600 80 110 ... 0 0 0]
 [680 80 160 ... 0 0 0]
 [600 80 110 ... 0 0 1]]


In [91]:
print(Y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 

Разбиваем данные на обучающие и тестовые.

In [108]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=0)

Создаем функцию для вывода оценок моделей.

In [126]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

def print_estimation(estimator, y_train, y_pred):
    print("R^2 = ", estimator.score(X, Y))
    print("MSE = ", mean_squared_error(y_train, y_pred))
    print("RMSE = ", mean_squared_error(y_train, y_pred, squared=False))
    print("MAE = ", mean_absolute_error(y_train, y_pred))

# Линейная регрессия

## Регрессия

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

Обучим нашу модель.

In [131]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

Гиперпараметров нет.

## Оценка модели

Оценим качество модели с помощью R2, Mean Square Error(MSE), Root Mean Square Error(RMSE),  mean absolute error (MAE).

In [132]:
print_estimation(reg, y_train, reg.predict(X_train))

R^2 =  0.11827416345120212
MSE =  2.405798244964221
RMSE =  1.5510635850809666
MAE =  1.3292519851561875


Получаем не очень хороший коэффициент детерминации

# Регрессия дерева решений

## Регрессия

https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html

Обучим нашу модель.

In [163]:
from sklearn.tree import DecisionTreeRegressor 

reg = DecisionTreeRegressor(random_state = 0)
reg.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

## Поиск гиперпараметра

In [134]:
from sklearn.model_selection import GridSearchCV

parameters = { "max_depth": range(1,20),
              'max_features': range(2, 10) }

model = GridSearchCV(DecisionTreeRegressor(random_state=0), parameters).fit(X_train, y_train)
model.best_params_

{'max_depth': 2, 'max_features': 7}

## Оценка модели

Оценим качество модели с помощью R2, Mean Square Error(MSE), Root Mean Square Error(RMSE),  mean absolute error (MAE).

In [137]:
print_estimation(reg, y_train, reg.predict(X_train))

R^2 =  0.7061422727151627
MSE =  0.0015625
RMSE =  0.03952847075210474
MAE =  0.003125


Получаем неплохой коэффициент детерминации

# LASSO

## Регрессия

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html

Обучим модель Lasso

In [149]:
from sklearn.linear_model import Lasso

reg = Lasso()
reg.fit(X_train, y_train)

Lasso()

## Поиск гиперпараметра

In [162]:
from sklearn.model_selection import GridSearchCV
import numpy as np

parameters = { 'alpha': np.arange(0.1, 10, 0.05)}

model = GridSearchCV(Lasso(random_state=0), parameters).fit(X_train, y_train)
model.best_params_

{'alpha': 0.9500000000000003}

## Оценка модели

Оценим качество модели с помощью R2, Mean Square Error(MSE), Root Mean Square Error(RMSE),  mean absolute error (MAE).

In [145]:
print_estimation(reg, y_train, reg.predict(X_train))

R^2 =  0.0054023846315861546
MSE =  2.7083688308833054
RMSE =  1.6457122564055071
MAE =  1.4237410244469888


Получаем плохой коэффициент детерминации

# Гребневая регрессия

## Регрессия

Обучим нашу модель.

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html#sklearn.linear_model.Ridge

In [152]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=1.0)
reg.fit(X_train, y_train)

Ridge()

## Поиск гиперпараметра

In [165]:
from sklearn.model_selection import GridSearchCV
import numpy as np

parameters = { 'alpha': np.arange(0.1, 100, 0.05)}

model = GridSearchCV(Ridge(random_state=0), parameters).fit(X_train, y_train)
model.best_params_

{'alpha': 17.300000000000008}

## Оценка модели

Оценим качество модели с помощью R2, Mean Square Error(MSE), Root Mean Square Error(RMSE),  mean absolute error (MAE).

In [154]:
print_estimation(reg, y_train, reg.predict(X_train))

R^2 =  0.11801337266127265
MSE =  2.406136182864323
RMSE =  1.5511725187303709
MAE =  1.330385076596894


Получаем не очень хороший коэффициент детерминации

# Elastic Net регрессия

## Регрессия

Обучим нашу модель.

In [155]:
from sklearn.linear_model import ElasticNet

reg = ElasticNet(random_state=0)
reg.fit(X_train, y_train)

ElasticNet(random_state=0)

## Подбор гиперпараметров

In [159]:
parameters = {'alpha': np.arange(0.1,2,0.05), 'l1_ratio': np.arange(0.1, 1.1, 0.1)}

model = GridSearchCV(ElasticNet(random_state=0), parameters).fit(X_train, y_train)
model.best_params_

{'alpha': 0.1, 'l1_ratio': 0.1}

## Оценка модели

Оценим качество модели с помощью R2, Mean Square Error(MSE), Root Mean Square Error(RMSE),  mean absolute error (MAE).

In [160]:
print_estimation(reg, y_train, reg.predict(X_train))

R^2 =  0.004930692947667903
MSE =  2.7050421925942905
RMSE =  1.644701247216129
MAE =  1.4228115555756071


Получаем плохой коэффициент детерминации

# Вывод

Для более точного прогнозирования поколения покемонов нужно большее количество обучающих данных.

Наиболее хорошо себя проявил алгоритм регресии дерева решений.